# Generated by Django 6.0.7 on 2026-07-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("salaries", models.DecimalField(decimal_places=2, max_digits=12)),
                ("rent", models.DecimalField(decimal_places=2, max_digits=12)),
                ("water", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "ota_commissions",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("maintenance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("other_costs", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("room_revenue", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "food_and_beverage",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("other_income", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
